spring.application.name=ds-pedidos-rabbit

#BANCO DE DADOS
spring.database.url=jdbc:h2:mem:rabbit
spring.database.username=sa
spring.database.password=

#RABBITMQ CONFIG
spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672

#RABBITMQ CUSTOM CONFIG
rabbitmq.exchange.name=pedidos.pedido-criado